// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID     pgtype.UUID
	Name   string
	ApiKey string
}

type Service struct {
	ID            pgtype.UUID
	ProjectID     string
	ProjectBranch string
	Name          string
	NodePorts     []int32
	Ingress       pgtype.Text
}

type Volume struct {
	Identifier    pgtype.UUID
	VolumeName    string
	ProjectID     string
	ProjectBranch string
	Size          int32
}
