// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	Name   string
	ApiKey string
}

type Service struct {
	Name        string
	ProjectName string
	NodePorts   []int32
	Ingress     pgtype.Text
}

type Volume struct {
	Identifier  string
	VolumeName  string
	ProjectName string
}
