// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/querier.go -destination internal/database/queriermock.go -package database
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddUserToProject mocks base method.
func (m *MockQuerier) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToProject", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToProject indicates an expected call of AddUserToProject.
func (mr *MockQuerierMockRecorder) AddUserToProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToProject", reflect.TypeOf((*MockQuerier)(nil).AddUserToProject), ctx, arg)
}

// CheckProjectsTableExists mocks base method.
func (m *MockQuerier) CheckProjectsTableExists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProjectsTableExists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProjectsTableExists indicates an expected call of CheckProjectsTableExists.
func (mr *MockQuerierMockRecorder) CheckProjectsTableExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProjectsTableExists", reflect.TypeOf((*MockQuerier)(nil).CheckProjectsTableExists), ctx)
}

// CreateProject mocks base method.
func (m *MockQuerier) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, arg)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockQuerierMockRecorder) CreateProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockQuerier)(nil).CreateProject), ctx, arg)
}

// CreateService mocks base method.
func (m *MockQuerier) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", ctx, arg)
	ret0, _ := ret[0].(Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockQuerierMockRecorder) CreateService(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockQuerier)(nil).CreateService), ctx, arg)
}

// CreateVolume mocks base method.
func (m *MockQuerier) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", ctx, arg)
	ret0, _ := ret[0].(Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockQuerierMockRecorder) CreateVolume(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockQuerier)(nil).CreateVolume), ctx, arg)
}

// DeleteProject mocks base method.
func (m *MockQuerier) DeleteProject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockQuerierMockRecorder) DeleteProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockQuerier)(nil).DeleteProject), ctx, id)
}

// DeleteServiceById mocks base method.
func (m *MockQuerier) DeleteServiceById(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceById indicates an expected call of DeleteServiceById.
func (mr *MockQuerierMockRecorder) DeleteServiceById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceById", reflect.TypeOf((*MockQuerier)(nil).DeleteServiceById), ctx, id)
}

// DeleteServiceByName mocks base method.
func (m *MockQuerier) DeleteServiceByName(ctx context.Context, arg DeleteServiceByNameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceByName", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceByName indicates an expected call of DeleteServiceByName.
func (mr *MockQuerierMockRecorder) DeleteServiceByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceByName", reflect.TypeOf((*MockQuerier)(nil).DeleteServiceByName), ctx, arg)
}

// DeleteUnusedVolumes mocks base method.
func (m *MockQuerier) DeleteUnusedVolumes(ctx context.Context, arg DeleteUnusedVolumesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnusedVolumes", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnusedVolumes indicates an expected call of DeleteUnusedVolumes.
func (mr *MockQuerierMockRecorder) DeleteUnusedVolumes(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnusedVolumes", reflect.TypeOf((*MockQuerier)(nil).DeleteUnusedVolumes), ctx, arg)
}

// GetApiKeyExistance mocks base method.
func (m *MockQuerier) GetApiKeyExistance(ctx context.Context, apiKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyExistance", ctx, apiKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyExistance indicates an expected call of GetApiKeyExistance.
func (mr *MockQuerierMockRecorder) GetApiKeyExistance(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyExistance", reflect.TypeOf((*MockQuerier)(nil).GetApiKeyExistance), ctx, apiKey)
}

// GetProject mocks base method.
func (m *MockQuerier) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockQuerierMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockQuerier)(nil).GetProject), ctx, id)
}

// GetProjectBranches mocks base method.
func (m *MockQuerier) GetProjectBranches(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectBranches", ctx, projectID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectBranches indicates an expected call of GetProjectBranches.
func (mr *MockQuerierMockRecorder) GetProjectBranches(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectBranches", reflect.TypeOf((*MockQuerier)(nil).GetProjectBranches), ctx, projectID)
}

// GetProjectByName mocks base method.
func (m *MockQuerier) GetProjectByName(ctx context.Context, name string) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByName", ctx, name)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByName indicates an expected call of GetProjectByName.
func (mr *MockQuerierMockRecorder) GetProjectByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByName", reflect.TypeOf((*MockQuerier)(nil).GetProjectByName), ctx, name)
}

// GetProjectsByUser mocks base method.
func (m *MockQuerier) GetProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsByUser", ctx, userID)
	ret0, _ := ret[0].([]Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsByUser indicates an expected call of GetProjectsByUser.
func (mr *MockQuerierMockRecorder) GetProjectsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsByUser", reflect.TypeOf((*MockQuerier)(nil).GetProjectsByUser), ctx, userID)
}

// GetService mocks base method.
func (m *MockQuerier) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, id)
	ret0, _ := ret[0].(Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockQuerierMockRecorder) GetService(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockQuerier)(nil).GetService), ctx, id)
}

// GetServiceByName mocks base method.
func (m *MockQuerier) GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByName", ctx, arg)
	ret0, _ := ret[0].(Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByName indicates an expected call of GetServiceByName.
func (mr *MockQuerierMockRecorder) GetServiceByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByName", reflect.TypeOf((*MockQuerier)(nil).GetServiceByName), ctx, arg)
}

// GetServicesByProject mocks base method.
func (m *MockQuerier) GetServicesByProject(ctx context.Context, arg GetServicesByProjectParams) ([]Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByProject", ctx, arg)
	ret0, _ := ret[0].([]Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByProject indicates an expected call of GetServicesByProject.
func (mr *MockQuerierMockRecorder) GetServicesByProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByProject", reflect.TypeOf((*MockQuerier)(nil).GetServicesByProject), ctx, arg)
}

// GetServicesByUser mocks base method.
func (m *MockQuerier) GetServicesByUser(ctx context.Context, userID uuid.UUID) ([]GetServicesByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByUser", ctx, userID)
	ret0, _ := ret[0].([]GetServicesByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByUser indicates an expected call of GetServicesByUser.
func (mr *MockQuerierMockRecorder) GetServicesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByUser", reflect.TypeOf((*MockQuerier)(nil).GetServicesByUser), ctx, userID)
}

// GetUnusedVolumeIdentifiers mocks base method.
func (m *MockQuerier) GetUnusedVolumeIdentifiers(ctx context.Context, arg GetUnusedVolumeIdentifiersParams) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnusedVolumeIdentifiers", ctx, arg)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnusedVolumeIdentifiers indicates an expected call of GetUnusedVolumeIdentifiers.
func (mr *MockQuerierMockRecorder) GetUnusedVolumeIdentifiers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnusedVolumeIdentifiers", reflect.TypeOf((*MockQuerier)(nil).GetUnusedVolumeIdentifiers), ctx, arg)
}

// GetUserByApiKey mocks base method.
func (m *MockQuerier) GetUserByApiKey(ctx context.Context, apiKey string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByApiKey", ctx, apiKey)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByApiKey indicates an expected call of GetUserByApiKey.
func (mr *MockQuerierMockRecorder) GetUserByApiKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByApiKey", reflect.TypeOf((*MockQuerier)(nil).GetUserByApiKey), ctx, apiKey)
}

// GetVolumeIdentifier mocks base method.
func (m *MockQuerier) GetVolumeIdentifier(ctx context.Context, arg GetVolumeIdentifierParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeIdentifier", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeIdentifier indicates an expected call of GetVolumeIdentifier.
func (mr *MockQuerierMockRecorder) GetVolumeIdentifier(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeIdentifier", reflect.TypeOf((*MockQuerier)(nil).GetVolumeIdentifier), ctx, arg)
}

// IsUserInProject mocks base method.
func (m *MockQuerier) IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInProject", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInProject indicates an expected call of IsUserInProject.
func (mr *MockQuerierMockRecorder) IsUserInProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInProject", reflect.TypeOf((*MockQuerier)(nil).IsUserInProject), ctx, arg)
}

// SetServiceIngress mocks base method.
func (m *MockQuerier) SetServiceIngress(ctx context.Context, arg SetServiceIngressParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServiceIngress", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetServiceIngress indicates an expected call of SetServiceIngress.
func (mr *MockQuerierMockRecorder) SetServiceIngress(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServiceIngress", reflect.TypeOf((*MockQuerier)(nil).SetServiceIngress), ctx, arg)
}

// SetServiceNodePorts mocks base method.
func (m *MockQuerier) SetServiceNodePorts(ctx context.Context, arg SetServiceNodePortsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServiceNodePorts", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetServiceNodePorts indicates an expected call of SetServiceNodePorts.
func (mr *MockQuerierMockRecorder) SetServiceNodePorts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServiceNodePorts", reflect.TypeOf((*MockQuerier)(nil).SetServiceNodePorts), ctx, arg)
}
