// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/querier.go -destination internal/database/queriermock.go -package database
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddUserToProject mocks base method.
func (m *MockQuerier) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToProject", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToProject indicates an expected call of AddUserToProject.
func (mr *MockQuerierMockRecorder) AddUserToProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToProject", reflect.TypeOf((*MockQuerier)(nil).AddUserToProject), ctx, arg)
}

// CheckProjectsTableExists mocks base method.
func (m *MockQuerier) CheckProjectsTableExists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProjectsTableExists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProjectsTableExists indicates an expected call of CheckProjectsTableExists.
func (mr *MockQuerierMockRecorder) CheckProjectsTableExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProjectsTableExists", reflect.TypeOf((*MockQuerier)(nil).CheckProjectsTableExists), ctx)
}

// CreateKubernetesService mocks base method.
func (m *MockQuerier) CreateKubernetesService(ctx context.Context, arg CreateKubernetesServiceParams) (KubernetesService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubernetesService", ctx, arg)
	ret0, _ := ret[0].(KubernetesService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKubernetesService indicates an expected call of CreateKubernetesService.
func (mr *MockQuerierMockRecorder) CreateKubernetesService(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubernetesService", reflect.TypeOf((*MockQuerier)(nil).CreateKubernetesService), ctx, arg)
}

// CreateKubernetesVolume mocks base method.
func (m *MockQuerier) CreateKubernetesVolume(ctx context.Context, arg CreateKubernetesVolumeParams) (Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubernetesVolume", ctx, arg)
	ret0, _ := ret[0].(Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKubernetesVolume indicates an expected call of CreateKubernetesVolume.
func (mr *MockQuerierMockRecorder) CreateKubernetesVolume(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubernetesVolume", reflect.TypeOf((*MockQuerier)(nil).CreateKubernetesVolume), ctx, arg)
}

// CreateProject mocks base method.
func (m *MockQuerier) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, arg)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockQuerierMockRecorder) CreateProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockQuerier)(nil).CreateProject), ctx, arg)
}

// DeleteKubernetesServiceById mocks base method.
func (m *MockQuerier) DeleteKubernetesServiceById(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKubernetesServiceById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKubernetesServiceById indicates an expected call of DeleteKubernetesServiceById.
func (mr *MockQuerierMockRecorder) DeleteKubernetesServiceById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKubernetesServiceById", reflect.TypeOf((*MockQuerier)(nil).DeleteKubernetesServiceById), ctx, id)
}

// DeleteKubernetesServiceByName mocks base method.
func (m *MockQuerier) DeleteKubernetesServiceByName(ctx context.Context, arg DeleteKubernetesServiceByNameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKubernetesServiceByName", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKubernetesServiceByName indicates an expected call of DeleteKubernetesServiceByName.
func (mr *MockQuerierMockRecorder) DeleteKubernetesServiceByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKubernetesServiceByName", reflect.TypeOf((*MockQuerier)(nil).DeleteKubernetesServiceByName), ctx, arg)
}

// DeleteProject mocks base method.
func (m *MockQuerier) DeleteProject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockQuerierMockRecorder) DeleteProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockQuerier)(nil).DeleteProject), ctx, id)
}

// DeleteUnusedKubernetesVolumes mocks base method.
func (m *MockQuerier) DeleteUnusedKubernetesVolumes(ctx context.Context, arg DeleteUnusedKubernetesVolumesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnusedKubernetesVolumes", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnusedKubernetesVolumes indicates an expected call of DeleteUnusedKubernetesVolumes.
func (mr *MockQuerierMockRecorder) DeleteUnusedKubernetesVolumes(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnusedKubernetesVolumes", reflect.TypeOf((*MockQuerier)(nil).DeleteUnusedKubernetesVolumes), ctx, arg)
}

// GetApiKeyExistance mocks base method.
func (m *MockQuerier) GetApiKeyExistance(ctx context.Context, apiKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyExistance", ctx, apiKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyExistance indicates an expected call of GetApiKeyExistance.
func (mr *MockQuerierMockRecorder) GetApiKeyExistance(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyExistance", reflect.TypeOf((*MockQuerier)(nil).GetApiKeyExistance), ctx, apiKey)
}

// GetKubernetesProjectBranches mocks base method.
func (m *MockQuerier) GetKubernetesProjectBranches(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesProjectBranches", ctx, projectID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesProjectBranches indicates an expected call of GetKubernetesProjectBranches.
func (mr *MockQuerierMockRecorder) GetKubernetesProjectBranches(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesProjectBranches", reflect.TypeOf((*MockQuerier)(nil).GetKubernetesProjectBranches), ctx, projectID)
}

// GetKubernetesServiceByName mocks base method.
func (m *MockQuerier) GetKubernetesServiceByName(ctx context.Context, arg GetKubernetesServiceByNameParams) (KubernetesService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesServiceByName", ctx, arg)
	ret0, _ := ret[0].(KubernetesService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesServiceByName indicates an expected call of GetKubernetesServiceByName.
func (mr *MockQuerierMockRecorder) GetKubernetesServiceByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesServiceByName", reflect.TypeOf((*MockQuerier)(nil).GetKubernetesServiceByName), ctx, arg)
}

// GetKubernetesServicesByProject mocks base method.
func (m *MockQuerier) GetKubernetesServicesByProject(ctx context.Context, arg GetKubernetesServicesByProjectParams) ([]KubernetesService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesServicesByProject", ctx, arg)
	ret0, _ := ret[0].([]KubernetesService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesServicesByProject indicates an expected call of GetKubernetesServicesByProject.
func (mr *MockQuerierMockRecorder) GetKubernetesServicesByProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesServicesByProject", reflect.TypeOf((*MockQuerier)(nil).GetKubernetesServicesByProject), ctx, arg)
}

// GetKubernetesServicesByUser mocks base method.
func (m *MockQuerier) GetKubernetesServicesByUser(ctx context.Context, userID uuid.UUID) ([]GetKubernetesServicesByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesServicesByUser", ctx, userID)
	ret0, _ := ret[0].([]GetKubernetesServicesByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesServicesByUser indicates an expected call of GetKubernetesServicesByUser.
func (mr *MockQuerierMockRecorder) GetKubernetesServicesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesServicesByUser", reflect.TypeOf((*MockQuerier)(nil).GetKubernetesServicesByUser), ctx, userID)
}

// GetKubernetesVolumeIdentifier mocks base method.
func (m *MockQuerier) GetKubernetesVolumeIdentifier(ctx context.Context, arg GetKubernetesVolumeIdentifierParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubernetesVolumeIdentifier", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesVolumeIdentifier indicates an expected call of GetKubernetesVolumeIdentifier.
func (mr *MockQuerierMockRecorder) GetKubernetesVolumeIdentifier(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesVolumeIdentifier", reflect.TypeOf((*MockQuerier)(nil).GetKubernetesVolumeIdentifier), ctx, arg)
}

// GetProject mocks base method.
func (m *MockQuerier) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockQuerierMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockQuerier)(nil).GetProject), ctx, id)
}

// GetProjectById mocks base method.
func (m *MockQuerier) GetProjectById(ctx context.Context, id uuid.UUID) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectById", ctx, id)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectById indicates an expected call of GetProjectById.
func (mr *MockQuerierMockRecorder) GetProjectById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectById", reflect.TypeOf((*MockQuerier)(nil).GetProjectById), ctx, id)
}

// GetProjectByName mocks base method.
func (m *MockQuerier) GetProjectByName(ctx context.Context, name string) (Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByName", ctx, name)
	ret0, _ := ret[0].(Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByName indicates an expected call of GetProjectByName.
func (mr *MockQuerierMockRecorder) GetProjectByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByName", reflect.TypeOf((*MockQuerier)(nil).GetProjectByName), ctx, name)
}

// GetProjectsByUser mocks base method.
func (m *MockQuerier) GetProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsByUser", ctx, userID)
	ret0, _ := ret[0].([]Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsByUser indicates an expected call of GetProjectsByUser.
func (mr *MockQuerierMockRecorder) GetProjectsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsByUser", reflect.TypeOf((*MockQuerier)(nil).GetProjectsByUser), ctx, userID)
}

// GetUnusedKubernetesVolumeIdentifiers mocks base method.
func (m *MockQuerier) GetUnusedKubernetesVolumeIdentifiers(ctx context.Context, arg GetUnusedKubernetesVolumeIdentifiersParams) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnusedKubernetesVolumeIdentifiers", ctx, arg)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnusedKubernetesVolumeIdentifiers indicates an expected call of GetUnusedKubernetesVolumeIdentifiers.
func (mr *MockQuerierMockRecorder) GetUnusedKubernetesVolumeIdentifiers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnusedKubernetesVolumeIdentifiers", reflect.TypeOf((*MockQuerier)(nil).GetUnusedKubernetesVolumeIdentifiers), ctx, arg)
}

// GetUserByApiKey mocks base method.
func (m *MockQuerier) GetUserByApiKey(ctx context.Context, apiKey string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByApiKey", ctx, apiKey)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByApiKey indicates an expected call of GetUserByApiKey.
func (mr *MockQuerierMockRecorder) GetUserByApiKey(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByApiKey", reflect.TypeOf((*MockQuerier)(nil).GetUserByApiKey), ctx, apiKey)
}

// IsUserInProject mocks base method.
func (m *MockQuerier) IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInProject", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInProject indicates an expected call of IsUserInProject.
func (mr *MockQuerierMockRecorder) IsUserInProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInProject", reflect.TypeOf((*MockQuerier)(nil).IsUserInProject), ctx, arg)
}

// SetKubernetesServiceIngress mocks base method.
func (m *MockQuerier) SetKubernetesServiceIngress(ctx context.Context, arg SetKubernetesServiceIngressParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKubernetesServiceIngress", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKubernetesServiceIngress indicates an expected call of SetKubernetesServiceIngress.
func (mr *MockQuerierMockRecorder) SetKubernetesServiceIngress(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKubernetesServiceIngress", reflect.TypeOf((*MockQuerier)(nil).SetKubernetesServiceIngress), ctx, arg)
}

// SetKubernetesServiceNodePorts mocks base method.
func (m *MockQuerier) SetKubernetesServiceNodePorts(ctx context.Context, arg SetKubernetesServiceNodePortsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKubernetesServiceNodePorts", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKubernetesServiceNodePorts indicates an expected call of SetKubernetesServiceNodePorts.
func (mr *MockQuerierMockRecorder) SetKubernetesServiceNodePorts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKubernetesServiceNodePorts", reflect.TypeOf((*MockQuerier)(nil).SetKubernetesServiceNodePorts), ctx, arg)
}
