// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error
	CheckProjectsTableExists(ctx context.Context) (bool, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteServiceById(ctx context.Context, id uuid.UUID) error
	DeleteServiceByName(ctx context.Context, arg DeleteServiceByNameParams) error
	DeleteUnusedVolumes(ctx context.Context, arg DeleteUnusedVolumesParams) error
	GetApiKeyExistance(ctx context.Context, apiKey string) (bool, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectBranches(ctx context.Context, projectID uuid.UUID) ([]string, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	GetProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error)
	GetServicesByProject(ctx context.Context, arg GetServicesByProjectParams) ([]Service, error)
	GetServicesByUser(ctx context.Context, userID uuid.UUID) ([]GetServicesByUserRow, error)
	GetUnusedVolumeIdentifiers(ctx context.Context, arg GetUnusedVolumeIdentifiersParams) ([]uuid.UUID, error)
	GetUserByApiKey(ctx context.Context, apiKey string) (User, error)
	GetVolumeIdentifier(ctx context.Context, arg GetVolumeIdentifierParams) (uuid.UUID, error)
	IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error)
	SetServiceIngress(ctx context.Context, arg SetServiceIngressParams) error
	SetServiceNodePorts(ctx context.Context, arg SetServiceNodePortsParams) error
}

var _ Querier = (*Queries)(nil)
