// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  name, api_key, node_ports
) VALUES (
  $1, $2, NULL
)
RETURNING name, api_key, node_ports
`

type CreateProjectParams struct {
	Name   string
	ApiKey string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.ApiKey)
	var i Project
	err := row.Scan(&i.Name, &i.ApiKey, &i.NodePorts)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE name = $1
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteProject, name)
	return err
}

const getProject = `-- name: GetProject :one
SELECT name, api_key, node_ports FROM projects
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.ApiKey, &i.NodePorts)
	return i, err
}

const getProjectByApiKey = `-- name: GetProjectByApiKey :one
SELECT name, api_key, node_ports FROM projects
WHERE api_key = $1 LIMIT 1
`

func (q *Queries) GetProjectByApiKey(ctx context.Context, apiKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByApiKey, apiKey)
	var i Project
	err := row.Scan(&i.Name, &i.ApiKey, &i.NodePorts)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT name, api_key, node_ports FROM projects
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.Name, &i.ApiKey, &i.NodePorts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
  SET node_ports = $2
WHERE name = $1
RETURNING name, api_key, node_ports
`

type UpdateProjectParams struct {
	Name      string
	NodePorts []int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.NodePorts)
	var i Project
	err := row.Scan(&i.Name, &i.ApiKey, &i.NodePorts)
	return i, err
}
