// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToProject(ctx context.Context, arg AddUserToProjectParams) error
	CheckProjectsTableExists(ctx context.Context) (bool, error)
	CreateKubernetesService(ctx context.Context, arg CreateKubernetesServiceParams) (KubernetesService, error)
	CreateKubernetesVolume(ctx context.Context, arg CreateKubernetesVolumeParams) (Volume, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteKubernetesServiceById(ctx context.Context, id uuid.UUID) error
	DeleteKubernetesServiceByName(ctx context.Context, arg DeleteKubernetesServiceByNameParams) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteUnusedKubernetesVolumes(ctx context.Context, arg DeleteUnusedKubernetesVolumesParams) error
	GetApiKeyExistance(ctx context.Context, apiKey string) (bool, error)
	GetKubernetesProjectBranches(ctx context.Context, projectID uuid.UUID) ([]string, error)
	GetKubernetesServiceByName(ctx context.Context, arg GetKubernetesServiceByNameParams) (KubernetesService, error)
	GetKubernetesServicesByProject(ctx context.Context, arg GetKubernetesServicesByProjectParams) ([]KubernetesService, error)
	GetKubernetesServicesByUser(ctx context.Context, userID uuid.UUID) ([]GetKubernetesServicesByUserRow, error)
	GetKubernetesVolumeIdentifier(ctx context.Context, arg GetKubernetesVolumeIdentifierParams) (uuid.UUID, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectById(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	GetProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	GetUnusedKubernetesVolumeIdentifiers(ctx context.Context, arg GetUnusedKubernetesVolumeIdentifiersParams) ([]uuid.UUID, error)
	GetUserByApiKey(ctx context.Context, apiKey string) (User, error)
	IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error)
	SetKubernetesServiceIngress(ctx context.Context, arg SetKubernetesServiceIngressParams) error
	SetKubernetesServiceNodePorts(ctx context.Context, arg SetKubernetesServiceNodePortsParams) error
}

var _ Querier = (*Queries)(nil)
