apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus
  namespace: nimbus
  labels:
    app: nimbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimbus
  template:
    metadata:
      labels:
        app: nimbus
    spec:
      serviceAccountName: nimbus-sa
      containers:
        - name: nimbus
          image: docker.prayujt.com/nimbus # replace with custom registry
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DOMAIN
              value: <server host> # e.g. prayujt.com, specifies base to spin new ingresses
            - name: DB_USER
              value: <database username>
            - name: DB_PASSWORD
              value: <database password>
            - name: DB_HOST
              value: <database host>
            - name: DB_NAME
              value: <database name>
            - name: DB_PORT
              value: 5432
            - name: NIMBUS_STORAGE_CLASS
              value: <storage class> # storage class of the created PV
          args:
            - "server"
          volumeMounts:
            - mountPath: "/volumes" # must always be mounted to /volumes
              name: nimbus-volumes
      volumes:
        - name: nimbus-volumes
          persistentVolumeClaim:
            claimName: <pvc name> # create your own PVC that binds to the same PV as above, must also be ReadWriteMany
---
apiVersion: v1
kind: Service
metadata:
  name: nimbus
  namespace: nimbus
  labels:
    app: nimbus
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nimbus
  type: ClusterIP
